apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-chaos-controller-manager-target-namespace
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/chaos-mesh-chaos-controller-manager-target-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-mesh-chaos-controller-manager-target-namespace
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: default
