apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-example
spec:
  duration: '5s'
  scheduler:
    cron: '@every 10s'
  action: pod-kill
  mode: all
  selector:
    namespaces:
      - coba

