services:
   
  db:
    image: docker.io/mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: nimda
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_db_user
      MYSQL_PASSWORD: example_db_pass
  #  ports:
  #    - "3306:3306"
    #volumes:
     #- ./db:/docker-entrypoint-initdb.d
  
  web:
    image: openshift.image.registry/cobatomcat:9.0
    container_name: tomcat
    environment:
      JDBC_URL: jdbc:mysql://db:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: example_db_user
      JDBC_PASS: example_db_pass
    ports:
     - "8080:8080"
    links:
      - db
