networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.90.0.0/24
          gateway: 10.90.0.1

services:
  mysql:
    image: docker.io/mysql:latest
    container_name: mysql
    hostname: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: nimda
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_db_user
      MYSQL_PASSWORD: example_db_pass
    networks:
      default:
        ipv4_address: 10.90.0.1
  
  web1:
    image: tomcat:9.0
    container_name: tomcat1
    hostname: tomcat_primary
    environment:
      JDBC_URL: jdbc:mysql://mysql_server:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: example_db_user
      JDBC_PASS: example_db_pass
    ports:
      - "8085:8080"
      - "5109:5005"
    networks:
      default:
        ipv4_address: 10.90.0.7
    volumes:
      - /Users/thomas/IdeaProjects/tomcatOpenShift/logs:/usr/local/tomcat/logs/

  web2:
    image: tomcat:9.0
    container_name: tomcat2
    environment:
      JDBC_URL: jdbc:mysql://mysql_server:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: example_db_user
      JDBC_PASS: example_db_pass
    ports:
      - "8086:8080"
    networks:
      default:
        ipv4_address: 10.90.0.6

  web3:
    image: tomcat:9.0
    container_name: tomcat3
    environment:
      JDBC_URL: jdbc:mysql://mysql_server:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: example_db_user
      JDBC_PASS: example_db_pass
    ports:
      - "8087:8080"
    networks:
      default:
        ipv4_address: 10.90.0.5